In [2]:
print("AI is the future")

AI is the future


#### Comments


In [4]:
# print this is a data science class
print("this is a data science class")

this is a data science class


In [5]:
# add two plus two

In [6]:
print(2+2)

4


In [7]:
2 + 2

4

#### Variable

In [3]:
x = 5

In [4]:
x

5

In [5]:
x
3

3

In [7]:
print(x)
print(3)

5
3


In [8]:
firstname = "elizabeth"

In [11]:
firstname

'elizabeth'

In [10]:
a = "john"
b = 70

In [14]:
a, b = "john", 70

In [15]:
a

'john'

In [16]:
b

70

In [ ]:
# python variable name cannot start with a number
3star = "hello"

In [ ]:
#A python variable name cannot contain hyphen(-) 
my-var = 5

In [19]:
my_var = 5
my_var

5

In [21]:
x = 5
y = 10

In [22]:
x

5

In [23]:
y

10

In [24]:
x, y = 5, 10

In [26]:
print(x, y)

5 10


In [29]:
x = 10

In [30]:
x

10

In [31]:
x = 7

In [32]:
x

7

#### Data Types

#### INTERGER

In [35]:
x = 10

In [37]:
# any number or figure that doesn't contain a decimal is an integer 
type(x)

int

In [38]:
type(20)

int

#### FLOAT

In [39]:
# Float
y = 10.5

In [41]:
type(y)

float

In [42]:
type(15.1)

float

#### STRING

In [43]:
# string
myString = "Hello world"

In [44]:
type(myString)

str

In [45]:
type("I love real madrid 2005")

str

In [46]:
# you can,t use quotation mark for numbers 
b = "10"

In [47]:
type(b)

str

#### LIST

In [48]:
# List 
myList = [1, 3, 5, 10]

In [50]:
type(myList)

list

In [51]:
myListTwo = [12, "20", 5, 10]

In [52]:
type(myListTwo)

list

#### TUPLE

In [53]:
# Tuple
myTuple = (2, 3.2, "five")

In [54]:
print(myTuple)

(2, 3.2, 'five')


In [58]:
type((1, 3, 44, 50))

tuple

In [59]:
type(["Apple", "Banana", "Orange"])

list

#### DICTIONARY

In [61]:
# Dictionary
login = {"name":"John PK", "Password" : "john123"}
login

{'name': 'John PK', 'Password': 'john123'}

In [63]:
type(login)

dict

In [64]:
car = {"name" : "Lexus", "brand" : "E350", "color" : ["black", "white"]}

In [65]:
car

{'name': 'Lexus', 'brand': 'E350', 'color': ['black', 'white']}

In [66]:
type(car)

dict

#### BOOLEAN

In [70]:
# Boolean
x = 2<5
x

True

In [69]:
print(x)

True


In [71]:
y = 10>21
y

False

In [72]:
type(10>21)

bool

In [73]:
type(y)

bool

#### CASTING

In [74]:
a = 50

In [75]:
a

50

In [76]:
# Convert integer to string
str(a)

'50'

In [80]:
x = 24

In [83]:
# Convert integer to float
y = float(x)

In [84]:
y

24.0

In [102]:
a = "hello"

In [103]:
# you can't convert a text into an integer
int(a)

# Arithmetic Operators
* Addition
* Substraction
* Multiplication
* Division
* Exponentation/Exponential
* Modulus

### ADDITION

In [118]:
x = 3
y = 12

In [119]:
x + y

15

In [120]:
x + y - 2

13

### SUBSTACTION

In [114]:
a = 4
b = 2

In [116]:
a - b

2

In [117]:
b - a

-2

### DIVISION

In [121]:
c = 45
a = 5

In [122]:
c/a

9.0

In [123]:
20/4

5.0

### MULTIPLICATION

In [124]:
a = 10
b = 2

In [125]:
a*b

20

In [126]:
b*a

20

### EXPONENTIAL/EXPONENTATION

In [128]:
b = 5
a = 2

In [129]:
b**a

25

### MODULUS

In [130]:
a = 10
b = 3

In [131]:
a%b

1

In [132]:
12%4

0

#### ASSIGNMENT OPERATORS

In [133]:
x = 5

In [134]:
x

5

In [135]:
x = x + 5

In [136]:
x

10

In [141]:
y = 12

In [145]:
# y = y + 10 is same as y +=10c
y +=10
y

32

In [146]:
m = 2

In [147]:
# m = m + 7
m +=7
m

27

In [148]:
d = 25

In [149]:
# d = d - 5
d -=5

In [150]:
d

20

In [154]:
c = 100

In [155]:
# c= c / 4
c /=4
c

25.0

In [157]:
multiply = 15
a = 2

In [158]:
# multiply = multiply * a
multiply *=a

In [159]:
multiply

30

In [160]:
x = 60

In [161]:
# Not equals to
x !=20

True

In [162]:
20<30

True

In [1]:
a = 15
b = 10

In [2]:
b>a

False

In [3]:
a<b

False

In [4]:
a < 7 or b > 10

False

In [5]:
a > b or b < a

True

In [8]:
# a < 7 or b > 10
a < 7 | b < 10

False

In [9]:
# a > b and b < a
a > b & b < a

True

In [10]:
not(a < 7)

True

In [11]:
not(20 > 15)

False

In [12]:
c = 12
b = 5

In [14]:
# less than or equals to
c <= b

False

In [15]:
# Greater than or equals to
b >= a

False

In [17]:
24 < 2 and 5 > 5 or 70 <= 6 or 15 < 20 and 20 >= 20 or 34 <= 22 or 44 > 60 and 35 <= 70

True

### COLLECTING INPUT FROM USER

In [19]:
input("Enter your name")


Enter your name lizzy


'lizzy'

In [21]:
firstNumber = input("First Number")
secondNumber = input("Second Number")

First Number 5
Second Number 12


In [24]:
print(firstNumber)
print(secondNumber)

5
12


In [25]:
firstNumber

'5'

In [27]:
add = firstNumber + secondNumber
add

'512'

In [28]:
a = int(firstNumber)
b = int(secondNumber)

In [29]:
a

5

In [30]:
b

12

In [31]:
a + b

17

#### LIST

In [32]:
myList = [10, "Orange", 2.5, "apple"]
myList

[10, 'Orange', 2.5, 'apple']

In [33]:
myList[1]

'Orange'

In [34]:
myList[0]

10

In [35]:
myList[3]

'apple'

In [36]:
#Fetch the last item from the list
myList[-1]

'apple'

In [37]:
#Fetch the second to the last item from the list
myList[-2]

2.5

In [188]:
# selecting the first twonitems from the list
myList[0 : 1]

[2]

In [39]:
myList[0 : 2]

[10, 'Orange']

In [41]:
myList[0 : 3]

[10, 'Orange', 2.5]

In [44]:
print(myList[:2])
print(myList[:3])
print(myList[:4])
print(myList[:-2])  

[10, 'Orange']
[10, 'Orange', 2.5]
[10, 'Orange', 2.5, 'apple']
[10, 'Orange']


In [45]:
myList[2 : 4]

[2.5, 'apple']

In [46]:
myList[1 : 4]

['Orange', 2.5, 'apple']

In [47]:
print(myList[2:])

[2.5, 'apple']


In [48]:
myFruits = ["Orange", "Apple", "Kiwi", "Cherry", "Pineapple"]
myFruits

['Orange', 'Apple', 'Kiwi', 'Cherry', 'Pineapple']

#### APPEND METHOD
# Append method to add item to an existing list
# also meaning ADD by rows
# MERGE - MEANS TO ADD BY COLUMN

In [49]:
# Append method to add item to an existing list
myFruits.append("Guava")

In [50]:
myFruits

['Orange', 'Apple', 'Kiwi', 'Cherry', 'Pineapple', 'Guava']

In [51]:
myFruits[0] = "carrot"

In [52]:
myFruits

['carrot', 'Apple', 'Kiwi', 'Cherry', 'Pineapple', 'Guava']

In [53]:
myFruits[-1] = "Grape"

In [54]:
myFruits

['carrot', 'Apple', 'Kiwi', 'Cherry', 'Pineapple', 'Grape']

#### REMOVE METHOD

In [56]:
# Remove an item from a list
myFruits.remove("Kiwi")

In [57]:
myFruits

['carrot', 'Apple', 'Cherry', 'Pineapple', 'Grape']

#### INSERT METHOD

In [59]:
# Insert an item to a list
myFruits.insert(2, "Banana")

In [60]:
myFruits

['carrot', 'Apple', 'Banana', 'Cherry', 'Pineapple', 'Grape']

#### CLEAR METHOD

In [61]:
# Clear all items in a list
myFruits.clear()

In [62]:
myFruits

[]

### IF ELSE STATEMENT

In [50]:
numbers = 11

In [57]:
#if else satement
if numbers % 2 == 0:
    print("even")
else:
    print("odd")

even


In [56]:
numbers = 4

#### IF ELSE STATEMENT

In [59]:
x = 10

In [60]:
if x == 20:
    print("x is twenty")

In [61]:
if x <= 20:
    print("x is twenty")

x is twenty


In [62]:
score = 30

In [63]:
if score > 50:
    print("pass")
else:
    print("fail")

fail


In [72]:
username = "lizzy"
password = "lizzy123"

In [75]:
if username == "lizzy" and password == "lizzy1234":
    print("Login successful")
else:
     print("Login error!!, check username or password")



Login error!!, check username or password


In [76]:
if username == "lizzy" and password == "lizzy123":
    print("Login successful")
else:
     print("Login error!!, check username or password")


Login successful


#### IF ELIF ELSE STATEMENT

In [77]:
age = 25

In [80]:
if age <= 17:
    print("Adolescent")
elif age <= 49:
    print("Adult")
else:
    print("Old")

Adult


In [81]:
a = 30
b = 24
c = 50

In [83]:
if a > b or b > c:
    print("Something")

Something


In [84]:
if a < b or c < a:
    print("Something")

In [85]:
if a < b or c < a:
    print("condition is true")
else:
    print("condition is false")


condition is false


In [86]:
myList = [12, 1, 82]

In [87]:
# Number of items inside a list
len(myList)

3

#### DICTIONARY

In [88]:
Userdetails = {"Name" : "John", "Color" : "Black", "State" : "Enugu"}

In [89]:
Userdetails["Name"]

'John'

In [90]:
Userdetails["State"]

'Enugu'

### UPDATE METHOD
Used to add new items to a dictionary

In [100]:
# Add a new key value called sex to the dictionary Userdetails
Userdetails.update({"Sex" : "Male"})

In [101]:
Userdetails

{'Name': 'John', 'Color': 'Black', 'State': 'Calabar', 'Sex': 'Male'}

In [102]:
# change state from Enugu to Calabar
Userdetails['State'] = "Calabar"

In [103]:
Userdetails

{'Name': 'John', 'Color': 'Black', 'State': 'Calabar', 'Sex': 'Male'}

In [104]:
Userdetails['Age'] = 35

In [105]:
Userdetails

{'Name': 'John',
 'Color': 'Black',
 'State': 'Calabar',
 'Sex': 'Male',
 'Age': 35}

### REMOVE METHOD
From dictionary

In [106]:
# Remove from dictionary
Userdetails.pop("Color")


'Black'

In [107]:
Userdetails

{'Name': 'John', 'State': 'Calabar', 'Sex': 'Male', 'Age': 35}

In [108]:
Userdetails.pop("Age")

35

In [110]:
Userdetails

{'Name': 'John', 'State': 'Calabar', 'Sex': 'Male'}

In [113]:
# Remove all item from a dictionary
Userdetails.clear()

In [114]:
Userdetails

{}

### KEY METHOD

In [134]:
### callout all the keys in the ditionary
Userdetails = {"Name" : "John", "Color" : "Black", "State" : "Enugu"}
Userdetails.keys()

dict_keys(['Name', 'Color', 'State'])

### VALUE METHOD

In [135]:
Userdetails.values()

dict_values(['John', 'Black', 'Enugu'])

### WHILE LOOP

In [118]:
#Even numbers from 2 to 20
i = 2
while i <= 20:
  print(i)
  i = i + 2
   

2
4
6
8
10
12
14
16
18
20


In [119]:
# Odd numbers from 1 to 50
i = 1
while i < 50:
  print(i)
  i = i + 2

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49


In [121]:
#Even numbers from 2 to 100
i = 2
while i <= 100:
  print(i)
  i = i + 2

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [123]:
# Odd numbers from 1 to 100
i = 1
while i <= 100:
  print(i)
  i += 2

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


### FOR LOOPS

In [125]:
fruits = ["Mango", "Apple", "Orange"]
for item in fruits:
  print(item)


Mango
Apple
Orange


In [126]:
# Loop through a string
for x in "Orange":
    print(x)

O
r
a
n
g
e


In [127]:
myList = [2, 4, 7, 9]

In [149]:
for y in myList:
    print(y ** 2)

4
16
49
81


In [150]:
myRange = range(6)

In [152]:
for y in myRange:
    print(y)

0
1
2
3
4
5


In [154]:
# Range with a start and stop value
myRangeTwo = range(2, 10)

In [155]:
for x in myRangeTwo :
    print(x)

2
3
4
5
6
7
8
9


In [136]:
# For loop through a dictionary
myDict = {"sex" : "M", "Age" : 50}

In [137]:
for x in myDict:
    print(x)

sex
Age


In [138]:
myDict.items()

dict_items([('sex', 'M'), ('Age', 50)])

In [143]:
# For loop through  both keys and values
for x, y in myDict.items():
    print(x,y)

sex M
Age 50


In [146]:
# For loop over/through a dict values
for x in myDict.values():
    print(x)

M
50


In [147]:
# For loop over/through a dict keys
for x in myDict.keys():
    print(x)

sex
Age


### FUNCTION 

In [156]:
print("Hello world")

Hello world


In [157]:
def myFunction():
    print("Hello world")

In [159]:
myFunction()

Hello world


In [161]:
def name(x):
    print(x)

In [162]:
name("Ahmad")

Ahmad


In [163]:
print("Ahmad")

Ahmad


In [164]:
number = 1
if number % 2 == 0:
    print("Even")
else:
    print("Odd")

Odd


In [167]:
def Even_Odd(x):
    if x % 2 == 0:
       print("Even")
    else:
        print("Odd")

In [168]:
Even_Odd(4)

Even


In [169]:
Even_Odd(9)

Odd


In [170]:
a = 19
b = 5

In [171]:
a + b

24

In [172]:
# Add a function that add two numbers together
def sum(x, y):
    print(x+y)

In [174]:
sum(10, 25)

35


In [176]:
sum(5, 2)

7


In [177]:
# Add a function thst subtract numbers together
def sub(x,y):
    print(x-y)

In [179]:
sub(40, 20)

20


### Create a function called login. The function would take in the user's username and password, then compare it with the system login details. If the details match, the system should say Login successful, else invalid login details

In [181]:
def Login(username, password):
    if username == "lizzy" and password == "lizzy123":
        print("Login successful")
    else:
        print("invalid login details!!!")
    

In [182]:
Login("lizzy", "lizzy123")

Login successful


In [183]:
Login("lizzy", "lizzy1234")

invalid login details!!!


In [184]:
Login("LIZZy", "lizzy1234")

invalid login details!!!


In [186]:
#Area of a triangle
def triangle(b, h):
    area = 0.5 * b * h
    return area

In [187]:
triangle(8, 150)

600.0

In [190]:
def triangle(b, h):
    area = 0.5 * b * h
    print(area)

In [191]:
triangle(20, 50)

500.0


### STRING

In [192]:
myString = "Hello world"
myString

'Hello world'

In [193]:
myString[:4]

'Hell'

In [194]:
myString[2:]

'llo world'

In [195]:
myString[:-1]

'Hello worl'

In [196]:
myString[:]

'Hello world'

In [197]:
myString[0]

'H'

In [198]:
len(myString)

11

In [199]:
len("this is a string")

16

In [202]:
"hello" * 2

'hellohello'

In [207]:
"liz " + "adeb"

'liz adeb'

In [208]:
x = "liz"

In [209]:
print("My name is " + x)

My name is liz


In [210]:
firstname = "John"
lastname = "Doe"

In [211]:
firstname + lastname

'JohnDoe'

In [212]:
firstname + " " + lastname

'John Doe'

### STRING METHOD

In [213]:
# Upper method would transform a string from the case to upper case
firstname

'John'

In [214]:
firstname.upper()

'JOHN'

In [216]:
firstname

'John'

In [217]:
m = lastname.upper()

In [218]:
lastname

'Doe'

In [219]:
m

'DOE'

In [220]:
firstname = firstname.lower()

In [221]:
firstname

'john'

### STRIP() METHOD

In [222]:
# Strip method to remove unwanted or unecessary empty spaces from a string
myString = "      This string contains unecessary       empty space   "

In [223]:
myString

'      This string contains unecessary       empty space   '

In [224]:
myString.strip()

'This string contains unecessary       empty space'

In [225]:
# ' '.join(myString.strip())

### REPLACE()METHOD

In [228]:
# Replace also known as a substitute
footballTeam = "I love Madrid football team"

In [229]:
footballTeam.replace("Madrid", "Real Madrid")

'I love Real Madrid football team'

### SPLIT() METHOD

In [230]:
# split method splits a string usimg a conditiom e.g by hyphen e.t.c. The output is a list
myString = "This is a string"

In [231]:
myString.split(" ")

['This', 'is', 'a', 'string']

In [232]:
stringTwo = "Ajayi-Tobi"

In [233]:
stringTwo.split("-")

['Ajayi', 'Tobi']

In [235]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 2.0 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.6 MB 1.5 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.6 MB 2.6 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.6 MB 3.0 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.6 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.6 MB 4.6 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 5.1 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.6 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 5.7 MB/s eta 0:00:01
   ----------------------

In [237]:
import numpy as np

In [238]:
a = [1, 2, 5, 7, 9]

### ARRAY() METHOD

In [244]:
my_arr = np.array(a)

In [245]:
my_arr

array([1, 2, 5, 7, 9])

In [246]:
type(my_arr)

numpy.ndarray

In [247]:
# Creating a zero dimensional array
arr = np.array(50)
arr

array(50)

In [257]:
# one dimensional array
np.array([1,2,34])

array([ 1,  2, 34])

In [258]:
[[2, 4, 6, 9], [12, 23, 34, 10]]

[[2, 4, 6, 9], [12, 23, 34, 10]]

In [259]:
# 2D array
np.array([[2, 4, 6, 9], [12, 23, 34, 10]])

array([[ 2,  4,  6,  9],
       [12, 23, 34, 10]])

In [260]:
# Check for array dimension
np.array([[2, 4, 6, 9]]).ndim

2

### Array indexing

In [261]:
my_arr[1]

np.int64(2)

In [262]:
my_arr[-1]

np.int64(9)

In [263]:
my_arr[1:3]

array([2, 5])

In [264]:
my_arr[1] + my_arr[4]

np.int64(11)

In [269]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [270]:
arr[0]

array([1, 2, 3, 4, 5])

In [271]:
arr[0, 2]

np.int64(3)

In [272]:
arr[1, 3]

np.int64(9)

In [273]:
#3D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [274]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [291]:
arr= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) 

In [292]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [293]:
arr[0,1,1]

np.int64(5)

In [294]:
arr[1,0,2]

np.int64(3)

### SHAPE

In [295]:
arr.shape

(2, 2, 3)

In [296]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [297]:
arr.shape

(2, 5)

### RESHAPE METHOD

In [306]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [307]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [308]:
arr.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [309]:
arr.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [310]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:2])

[1 2]


## QUESTIONS
* Create a 1-D numpy array with elements from 1-6
* Create a 2-D numpy array with shape of (3, 3)
* Given `arr= np.array(10, 20, 30, 40)`. Retrieve the third item/elememt. Retrieve the last element
* Given `arr_two = np.array([[1,2,3], [4,5,6], [7,8,9]])`.  Retrieve the element in the second row, third column. Retrieve the entire first row
* Reshape the 1D array created in question one into another dimension
* Reshape the 2D array created in question two into another dimension

In [353]:
#1 Create a 1-D numpy array with elements from 1-6
arr = np.array([1,2,3,4,5,6,])

In [354]:
arr

array([1, 2, 3, 4, 5, 6])

In [356]:
#5 Reshape the 1D array created in question one into another dimension
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [362]:
#2Create a 2-D numpy array with shape of (3, 3)
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [368]:
#6 Reshape the 2D array created in question two into another dimension
arr.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [336]:
arr.shape

(3, 3)

In [339]:
#3 Given arr= np.array(10, 20, 30, 40). Retrieve the third item/elememt. Retrieve the last element
arr = np.array([10, 20, 30, 40])

In [340]:
arr[2]

np.int64(30)

In [341]:
arr[3]

np.int64(40)

In [348]:
#4 Given arr_two = np.array([[1,2,3], [4,5,6], [7,8,9]]). Retrieve the element in the second row, third column. Retrieve the entire first row
arr_two = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [349]:
arr_two[1, 2]

np.int64(6)

In [350]:
arr_two[0]

array([1, 2, 3])

In [369]:
# Arithmetic operations on arrays
a = np.array([2, 3, 5, 8])
b = np.array([1, 9, 5, 10])

In [370]:
print(a.shape)
print(b.shape)

(4,)
(4,)


In [371]:
print(a)
print(b)

[2 3 5 8]
[ 1  9  5 10]


In [372]:
a + b

array([ 3, 12, 10, 18])

In [373]:
a * b

array([ 2, 27, 25, 80])

In [374]:
a / b

array([2.        , 0.33333333, 1.        , 0.8       ])

### ADD METHOD

In [375]:
# a + b
np.add(a, b)

array([ 3, 12, 10, 18])

### SUBTRACT()METHOD

In [376]:
# a - b
np.subtract(a, b)

array([ 1, -6,  0, -2])

### MULTIPLY()METHOD

In [377]:
# a * b
np.multiply(a, b)

array([ 2, 27, 25, 80])

### PROD()METHOD

In [378]:
a

array([2, 3, 5, 8])

In [379]:
# Dot product
np.prod(a)

np.int64(240)

### MAX()METHOD

In [380]:
a

array([2, 3, 5, 8])

In [381]:
#find the maximum value of an array
np.max(a)

np.int64(8)

### MIN()METHOD

In [382]:
a

array([2, 3, 5, 8])

In [383]:
#find the minimum value of an array
np.min(a)

np.int64(2)

### MEAN()METHOD

In [384]:
#find the average/mean value of an array
np.mean(a)

np.float64(4.5)

### MEDIAN()METHOD

In [385]:
np.median(a)

np.float64(4.0)

### PANDA

In [402]:
!pip install panda

In [403]:
import pandas as pd

### SERIES METHOD

In [405]:
a = [1, 20, 23, 50]

In [407]:
mySeries = pd.Series(a)
mySeries

0     1
1    20
2    23
3    50
dtype: int64

In [408]:
mySeries[1]

np.int64(20)

In [409]:
mySeriesTwo = pd.Series(a, index= [ "a", "b", "c", "d"])

In [410]:
mySeriesTwo

a     1
b    20
c    23
d    50
dtype: int64

In [411]:
mySeriesTwo['a']

np.int64(1)

In [412]:
# How to creat a Panda series from a dictionary
myDict = {'Name' : 'John', 'Age' : 17, 'State' : 'Rivers'}
myDict


{'Name': 'John', 'Age': 17, 'State': 'Rivers'}

In [414]:
mySeriesThree = pd.Series(myDict)

In [415]:
mySeriesThree

Name       John
Age          17
State    Rivers
dtype: object

In [416]:
mySeriesThree['Name']

'John'

In [417]:
# Dataframe
exercise = {
    "calories": [100, 150, 200, 250],
    "minutes": [30, 45, 200, 70]
}

In [418]:
exercise

{'calories': [100, 150, 200, 250], 'minutes': [30, 45, 200, 70]}

In [419]:
df = pd.DataFrame(exercise)


In [420]:
df

calories  minutes
0       100       30
1       150       45
2       200      200
3       250       70

In [422]:
# Fetch all values under calories
df['calories']

0    100
1    150
2    200
3    250
Name: calories, dtype: int64

In [423]:
df.calories

0    100
1    150
2    200
3    250
Name: calories, dtype: int64

In [424]:
# df[0]

In [425]:
df.loc[0]

calories    100
minutes      30
Name: 0, dtype: int64

In [427]:
details = {
    "firstName" : ["John", "Dayo", "Chika"],
    "lastName" : ["Johnson", "Seyi", "Kingsley"],
    "Age" : [25, 32, 19],
    "Department" : ["Sales", "IT", "Editorial"]
}

In [428]:
# Create a dataframe from the dictionary above and call it employee_details
# Fetch all data from the created dataframe above
# Fetch out evry record in the firstname
# Fetch the last record of all the column names from the dataframe

In [446]:
# Create a dataframe from the dictionary above and call it employee_details
employee_details = pd.DataFrame(details)
employee_details

firstName  lastName  Age Department
0      John   Johnson   25      Sales
1      Dayo      Seyi   32         IT
2     Chika  Kingsley   19  Editorial

In [450]:
# Fetch all data from the created dataframe above
employee_details

firstName  lastName  Age Department
0      John   Johnson   25      Sales
1      Dayo      Seyi   32         IT
2     Chika  Kingsley   19  Editorial

In [460]:
# Fetch out evry record in the firstname
employee_details.firstName

0     John
1     Dayo
2    Chika
Name: firstName, dtype: object

In [470]:
employee_details.loc[2]

firstName         Chika
lastName       Kingsley
Age                  19
Department    Editorial
Name: 2, dtype: object

In [474]:
employee_details.firstName[2]

'Chika'

In [511]:
# Employee Age above 30
employee_details['Age'] > 30

0    False
1     True
2    False
Name: Age, dtype: bool

In [512]:
employee_details[employee_details['Age'] > 30]

firstName lastName  Age Department
1      Dayo     Seyi   32         IT

In [513]:
# Employee Age above 30
employee_details[employee_details['Age'] > 30] ['Age']

1    32
Name: Age, dtype: int64

In [514]:
employee_details[employee_details['Department'] == "Sales" ] 

firstName lastName  Age Department
0      John  Johnson   25      Sales

In [516]:
a = employee_details['Age'] > 20
b = employee_details['Department'] == "IT" 

In [517]:
employee_details[a | b]

firstName lastName  Age Department
0      John  Johnson   25      Sales
1      Dayo     Seyi   32         IT

### ADD NEW COLUMN TO AN EXISTING DATAFRAME

In [518]:
employee_details

firstName  lastName  Age Department
0      John   Johnson   25      Sales
1      Dayo      Seyi   32         IT
2     Chika  Kingsley   19  Editorial

In [519]:
employee_details['Salary'] = [100000, 250000, 170000]

In [520]:
employee_details

firstName  lastName  Age Department  Salary
0      John   Johnson   25      Sales  100000
1      Dayo      Seyi   32         IT  250000
2     Chika  Kingsley   19  Editorial  170000